---
title: "R Notebook"
output: html_notebook
---
```{r}
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))
```

```{r}
library(tidyverse)
library(dplyr)
library(tidyjson)
library(Cairo)
```
## First Plots

```{r}
path_mzn = "./outputs_mzn"

mzn_files = unlist(list.files(path_mzn, pattern = "*.json") %>%
  lapply(function (t) paste(path_mzn,t, sep="/")))

mzn_out = 
  mzn_files %>% 
  map_df(
    function(t)
      read_json(t) %>%
        spread_all() %>%
        as_tibble() %>%
        select(-document.id)
  )

mzn_out = mzn_out %>%
  select(-sol) %>%
  mutate(file_path=unlist(mzn_files)) %>%
  mutate(num = row_number() - 1) %>%
  select(num, file_path, everything())

View(mzn_out)
```

```{r}
path_lp = "./outputs_lp"

lp_files = unlist(list.files(path_lp, pattern = "*.json") %>%
  lapply(function (t) paste(path_lp,t, sep="/")))

lp_out = 
  lp_files %>% 
  map_df(
    function(t)
      read_json(t) %>%
        spread_all() %>%
        as_tibble() %>%
        select(-document.id)
  )

lp_out = lp_out %>%
  select(-sol) %>%
  mutate(file_path=unlist(lp_files)) %>%
  mutate(num = row_number() - 1) %>%
  select(num, file_path, everything())

View(lp_out)
```


```{r}
outputs = rbind(mzn_out, lp_out)
View(outputs)
```

```{r}
outputs %>%
  ggplot(aes(x=num, y=time, color=model_type)) +
  geom_line()
```
```{r}
mzn_timeouted =
  outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'MZN')

lp_timeouted =
  outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'LP')

outputs %>%
  ggplot(aes(x=num, y=solveTime, color=model_type)) +
  geom_line() +
  geom_point(mzn_timeouted, mapping=aes(x=num, y=rep(-5 ,nrow(mzn_timeouted)), color=model_type), show.legend = F) +
  geom_point(lp_timeouted,  mapping=aes(x=num, y=rep(-10,nrow(lp_timeouted )), color=model_type), show.legend = F)
```
## Sorted By solveTime

```{r}
sorted_mzn_out = mzn_out %>%
  arrange(solveTime) %>%
  mutate(num = row_number() - 1)

sorted_lp_out = lp_out %>%
  arrange(solveTime) %>%
  mutate(num = row_number() - 1)
  
  
sorted_outputs = rbind(sorted_mzn_out, sorted_lp_out)
```


```{r}
mzn_timeouted =
  sorted_outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'MZN')

lp_timeouted =
  sorted_outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'LP')

sorted_outputs %>%
  ggplot(aes(x=num, y=solveTime, color=model_type)) +
  geom_line() +
  geom_point(mzn_timeouted, mapping=aes(x=num, y=rep(-5 ,nrow(mzn_timeouted)), color=model_type), show.legend = F) +
  geom_point(lp_timeouted,  mapping=aes(x=num, y=rep(-10,nrow(lp_timeouted )), color=model_type), show.legend = F)

sorted_outputs %>%
  ggplot(aes(x=num, y=time, color=model_type)) +
  geom_line() +
  geom_point(mzn_timeouted, mapping=aes(x=num, y=rep(-5 ,nrow(mzn_timeouted)), color=model_type), show.legend = F) +
  geom_point(lp_timeouted,  mapping=aes(x=num, y=rep(-10,nrow(lp_timeouted )), color=model_type), show.legend = F)
```

## Sorted By time

```{r}
sorted_mzn_out = mzn_out %>%
  arrange(time) %>%
  mutate(num = row_number() - 1)

sorted_lp_out = lp_out %>%
  arrange(time) %>%
  mutate(num = row_number() - 1)
  
  
sorted_outputs = rbind(sorted_mzn_out, sorted_lp_out)
```


```{r}
mzn_timeouted =
  sorted_outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'MZN')

lp_timeouted =
  sorted_outputs %>%
    filter(timeouted) %>%
    filter(model_type == 'LP')

Cairo(600, 600, file="solveTimes.png", type="png", bg="white")
sorted_outputs %>%
  ggplot(aes(x=num, y=solveTime, color=model_type)) +
  geom_line() +
  geom_point(mzn_timeouted, mapping=aes(x=num, y=rep(-5 ,nrow(mzn_timeouted)), color=model_type), show.legend = F) +
  geom_point(lp_timeouted,  mapping=aes(x=num, y=rep(-10,nrow(lp_timeouted )), color=model_type), show.legend = F)

Cairo(600, 600, file="times.png", type="png", bg="white")
sorted_outputs %>%
  ggplot(aes(x=num, y=time, color=model_type)) +
  geom_line() +
  geom_point(mzn_timeouted, mapping=aes(x=num, y=rep(-5 ,nrow(mzn_timeouted)), color=model_type), show.legend = F) +
  geom_point(lp_timeouted,  mapping=aes(x=num, y=rep(-10,nrow(lp_timeouted )), color=model_type), show.legend = F)
```



























